import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';

import { getApiResponseErrorMsg } from '@services/api.service';

import { mockGetFeaturedBibleVerse, mockUpdateFeaturedBibleVerse } from './api';

import type { FeaturedBibleVerse } from './types';

/*
 * Centralized query keys prevent string duplication and make future
 * invalidation easier.
 *
 * Examples:
 * - bibleVerseQueryKeys.all
 * - bibleVerseQueryKeys.featured()
 */
export const bibleVerseQueryKeys = {
    all: ['rccgmznl', 'bible-verses'] as const,

    featured: () => [...bibleVerseQueryKeys.all, 'featured'] as const,
};

/*
 * Retrieve the currently featured Bible verse.
 *
 * The request either resolves with a complete FeaturedBibleVerse or
 * throws an Error. React Query will place thrown errors into the
 * query's error state.
 *
 * TODO: Replace the mock request with the production API request.
 */
async function getFeaturedBibleVerse(): Promise<FeaturedBibleVerse> {
    const response = await mockGetFeaturedBibleVerse();

    if (!response.success || !response.data) {
        throw new Error(
            getApiResponseErrorMsg(
                response,
                'Failed to fetch featured Bible verse'
            )
        );
    }

    return response.data;
}

/*
 * Update the featured Bible verse and return the canonical version
 * provided by the server.
 *
 * Using the server response ensures the cache receives any values
 * normalized or generated by the backend.
 *
 * TODO: Replace the mock request with the production API request.
 */
async function updateFeaturedBibleVerse(
    payload: FeaturedBibleVerse
): Promise<FeaturedBibleVerse> {
    const response = await mockUpdateFeaturedBibleVerse(payload);

    if (!response.success || !response.data) {
        throw new Error(
            getApiResponseErrorMsg(
                response,
                'Failed to update featured Bible verse'
            )
        );
    }

    return response.data;
}

/*
 * Query the currently featured Bible verse.
 *
 * The verse changes infrequently, so cached data remains fresh for
 * 30 minutes. Unused cached data is retained for two hours before
 * being garbage-collected.
 *
 * Window-focus refetching is disabled to avoid unnecessary requests
 * whenever the user returns to the browser tab. Reconnect refetching
 * remains enabled so stale data can recover after a network outage.
 */
export function useFeaturedBibleVerse() {
    return useQuery<FeaturedBibleVerse>({
        queryKey: bibleVerseQueryKeys.featured(),
        queryFn: getFeaturedBibleVerse,

        staleTime: 30 * 60 * 1000,
        gcTime: 2 * 60 * 60 * 1000,

        retry: 2,

        refetchOnWindowFocus: false,
        refetchOnReconnect: true,
    });
}

/*
 * Update the featured Bible verse.
 *
 * Since the update endpoint returns the complete updated verse, the
 * successful response is written directly into the existing query
 * cache. Any component using useFeaturedBibleVerse will rerender
 * immediately without requiring another request or page reload.
 */
export function useUpdateFeaturedBibleVerse() {
    const queryClient = useQueryClient();

    return useMutation<FeaturedBibleVerse, Error, FeaturedBibleVerse>({
        mutationFn: updateFeaturedBibleVerse,

        onSuccess: (updatedVerse) => {
            queryClient.setQueryData<FeaturedBibleVerse>(
                bibleVerseQueryKeys.featured(),
                updatedVerse
            );
        },
    });
}
